language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: RfkJyCyCZLJEuU2RlUx1RxM9cXvHtcyOfz5AOgs7pDKoNHeSuO42XMCtNiMLjrg/HNgzPuZi008XWFW+EkNTXYiseFHWmKMdEPm5mDVlnBLGZSdOas3xAiStro+quYfUUtbNG3/kYfSSg3knNC0cES6NM30wfOqLicZnfyblDt4=
  app: qiitan-slack
  on:
    repo: increments/qiitan-rb
