source "https://rubygems.org"

gem "rake"
gem "ruboty-cron"
gem "ruboty-echo"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-ruby", ">= 0.0.2"
gem "ruboty-call", github: "a2ikm/ruboty-call", branch: "record_option"
gem "ruboty-contacts", github: "a2ikm/ruboty-contacts"
